import { Link } from "react-router-dom";

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="ft-footer">
      <style>{styles}</style>
      <div className="ft-inner">
        <div className="ft-top">
          <div className="ft-brand-col">
            <span className="ft-brand">
              <span className="ft-brand-mark">◆</span> VoltTrade
            </span>
            <p className="ft-tagline">
              Even/Odd and Over/Under digit contracts on a simulated synthetic index.
              Fund your account with M-Pesa or PayPal.
            </p>
          </div>

          <div className="ft-links-col">
            <span className="ft-heading">Platform</span>
            <Link to="/trade" className="ft-link">Trade</Link>
            <Link to="/wallet" className="ft-link">Wallet</Link>
            <Link to="/profile" className="ft-link">Profile</Link>
          </div>

          <div className="ft-links-col">
            <span className="ft-heading">Account</span>
            <Link to="/login" className="ft-link">Log in</Link>
            <Link to="/register" className="ft-link">Sign up</Link>
          </div>
        </div>

        <div className="ft-bottom">
          <p className="ft-disclaimer">
            Demo platform. Prices are generated by a deterministic simulated tick engine, not a real
            market. Nothing here is financial advice, and no real-world asset is being traded.
          </p>
          <p className="ft-copyright">© {year} VoltTrade. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}

const styles = `
.ft-footer {
  border-top: 1px solid var(--border);
  background: var(--surface);
  margin-top: 40px;
}
.ft-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding: 40px 20px 24px;
}
.ft-top {
  display: grid;
  grid-template-columns: 2fr 1fr 1fr;
  gap: 32px;
  padding-bottom: 28px;
  border-bottom: 1px solid var(--border);
}
@media (max-width: 640px) {
  .ft-top { grid-template-columns: 1fr; }
}

.ft-brand {
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 17px;
  display: flex;
  align-items: center;
  gap: 6px;
}
.ft-brand-mark {
  color: var(--even);
}
.ft-tagline {
  color: var(--muted);
  font-size: 13px;
  line-height: 1.5;
  margin: 10px 0 0;
  max-width: 340px;
}

.ft-links-col {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.ft-heading {
  color: var(--muted);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  margin-bottom: 4px;
}
.ft-link {
  color: var(--text);
  text-decoration: none;
  font-size: 13px;
}
.ft-link:hover {
  color: var(--even);
}

.ft-bottom {
  padding-top: 20px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.ft-disclaimer {
  color: var(--muted);
  font-size: 12px;
  line-height: 1.5;
  max-width: 680px;
  margin: 0;
}
.ft-copyright {
  color: var(--muted);
  font-size: 12px;
  margin: 0;
}
`;