import { Link } from "react-router-dom";

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="ft-footer">
      <style>{styles}</style>
      <div className="ft-inner">
        <div className="ft-top">
          <div className="ft-brand-col">
            <span className="ft-brand">SmartTrader</span>
            <p className="ft-tagline">
              Trade Even/Odd and Over/Under digit contracts on a simulated synthetic index.
              Fund your account with M-Pesa or PayPal.
            </p>
            <div className="ft-social">
              <a href="#" className="ft-social-link" aria-label="Twitter">
                <i className="bi bi-twitter-x"></i>
              </a>
              <a href="#" className="ft-social-link" aria-label="LinkedIn">
                <i className="bi bi-linkedin"></i>
              </a>
              <a href="#" className="ft-social-link" aria-label="Telegram">
                <i className="bi bi-telegram"></i>
              </a>
            </div>
          </div>

          <div className="ft-links-col">
            <span className="ft-heading">Platform</span>
            <Link to="/trade" className="ft-link">
              <i className="bi bi-graph-up"></i> Trade
            </Link>
            <Link to="/wallet" className="ft-link">
              <i className="bi bi-wallet2"></i> Wallet
            </Link>
            <Link to="/profile" className="ft-link">
              <i className="bi bi-person"></i> Profile
            </Link>
          </div>

          <div className="ft-links-col">
            <span className="ft-heading">Account</span>
            <Link to="/login" className="ft-link">
              <i className="bi bi-box-arrow-in-right"></i> Log in
            </Link>
            <Link to="/register" className="ft-link">
              <i className="bi bi-person-plus"></i> Sign up
            </Link>
          </div>
        </div>

        <div className="ft-bottom">
          <div className="ft-bottom-row">
            <p className="ft-disclaimer">
              <i className="bi bi-info-circle"></i>
              Demo platform. Prices are generated by a deterministic simulated tick engine, not a real
              market. Nothing here is financial advice, and no real-world asset is being traded.
            </p>
            <div className="ft-legal">
              <Link to="/terms" className="ft-legal-link">Terms</Link>
              <Link to="/privacy" className="ft-legal-link">Privacy</Link>
              <Link to="/support" className="ft-legal-link">Support</Link>
            </div>
          </div>
          <p className="ft-copyright">
            <i className="bi bi-c-circle"></i> {year} SmartTrader. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}

const styles = `
@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css");

.ft-footer {
  border-top: 1px solid rgba(255, 255, 255, 0.06);
  background: rgba(18, 24, 34, 0.8);
  backdrop-filter: blur(8px);
  margin-top: 40px;
}
.ft-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding: 48px 20px 24px;
}
.ft-top {
  display: grid;
  grid-template-columns: 2fr 1fr 1fr;
  gap: 40px;
  padding-bottom: 32px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}
@media (max-width: 768px) {
  .ft-top {
    grid-template-columns: 1fr 1fr;
    gap: 24px;
  }
}
@media (max-width: 480px) {
  .ft-top {
    grid-template-columns: 1fr;
    gap: 20px;
  }
}

.ft-brand-col {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.ft-brand {
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 20px;
  background: linear-gradient(135deg, #ffffff, #2dd4bf);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
.ft-tagline {
  color: rgba(255, 255, 255, 0.5);
  font-size: 14px;
  line-height: 1.6;
  margin: 0;
  max-width: 380px;
}

.ft-social {
  display: flex;
  gap: 12px;
  margin-top: 4px;
}
.ft-social-link {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  border: 1px solid rgba(255, 255, 255, 0.06);
  color: rgba(255, 255, 255, 0.4);
  text-decoration: none;
  transition: all 0.2s ease;
}
.ft-social-link i {
  font-size: 16px;
}
.ft-social-link:hover {
  background: rgba(45, 212, 191, 0.08);
  border-color: rgba(45, 212, 191, 0.2);
  color: #2dd4bf;
  transform: translateY(-2px);
}

.ft-links-col {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.ft-heading {
  color: rgba(255, 255, 255, 0.4);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-weight: 600;
  margin-bottom: 4px;
}
.ft-link {
  display: flex;
  align-items: center;
  gap: 8px;
  color: rgba(255, 255, 255, 0.6);
  text-decoration: none;
  font-size: 14px;
  padding: 4px 0;
  transition: all 0.2s ease;
}
.ft-link i {
  font-size: 14px;
  width: 18px;
}
.ft-link:hover {
  color: #2dd4bf;
  transform: translateX(4px);
}

.ft-bottom {
  padding-top: 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.ft-bottom-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 20px;
  flex-wrap: wrap;
}
@media (max-width: 640px) {
  .ft-bottom-row {
    flex-direction: column;
  }
}
.ft-disclaimer {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  color: rgba(255, 255, 255, 0.3);
  font-size: 12px;
  line-height: 1.6;
  margin: 0;
  max-width: 680px;
}
.ft-disclaimer i {
  font-size: 16px;
  flex-shrink: 0;
  margin-top: 2px;
  color: rgba(255, 255, 255, 0.2);
}

.ft-legal {
  display: flex;
  gap: 16px;
  flex-shrink: 0;
}
.ft-legal-link {
  color: rgba(255, 255, 255, 0.3);
  text-decoration: none;
  font-size: 12px;
  transition: color 0.2s ease;
}
.ft-legal-link:hover {
  color: #2dd4bf;
}

.ft-copyright {
  display: flex;
  align-items: center;
  gap: 6px;
  color: rgba(255, 255, 255, 0.2);
  font-size: 12px;
  margin: 0;
}
.ft-copyright i {
  font-size: 14px;
}
`;

export { Footer };